//! clap derive structs.

use std::path::PathBuf;

use clap::Parser;
use knf_dotted::PathLeaf;

use crate::format::Format;

#[derive(Parser, Debug)]
#[command(
    name = "knf",
    version,
    about = "Merge layered configuration files and print the result",
    long_about = "\
Merge layered configuration files and print the result.

Files are layers, merged left to right in argument order. JSON and TOML may be
mixed freely. Ordinary mode writes exactly one document to stdout.

  knf base.toml prod.toml
  knf base.json - --input-format json          # stdin as a layer
  knf defaults.json --set server.port=8080 -f toml
  knf env/*.toml x region/*.toml -o generated

Objects merge key by key. Arrays, scalars and null all replace wholesale —
null is an ordinary value that overwrites, not a delete instruction.

A positional `x` generates the Cartesian product of the alternatives on either
side. Product mode writes one merged file per combination to --output-dir and
prints the generated paths."
)]
pub struct Cli {
    /// Files to merge as layers; `x` separates product factors; `-` reads stdin
    #[arg(value_name = "FILE|x")]
    pub files: Vec<PathBuf>,

    /// Treat every input as this format; required for `-`
    #[arg(
        long,
        value_name = "FORMAT",
        long_help = "\
Treat every input as this format, overriding extension inference.

Required for `-`, which has no extension. Note that it applies to all inputs,
not only stdin, so it cannot be used to mix a stdin layer of one format with
files of another."
    )]
    pub input_format: Option<Format>,

    /// Inline terminal layer, applied after all files
    #[arg(
        long = "set",
        value_name = "KEY.PATH=VALUE",
        long_help = "\
Inline terminal layer, applied after all files. Repeatable; multiple --set apply
left to right in ordinary mode. In Cartesian-product mode, repeated --set
expressions are alternatives in one final factor.

The value is parsed as JSON, falling back to a string when that fails:

  port=8080       -> 8080     (number)
  debug=true      -> true     (bool)
  name=foo        -> \"foo\"    (not valid JSON, so a string)
  proxy=null      -> null     (an error under -f toml, like any other null)
  tags=[\"a\",\"b\"]  -> array
  tags=[a,b]      -> \"[a,b]\"  (not valid JSON, so a string)

Sharp edge: version=1.0 is the number 1.0, not the string \"1.0\". Force a string
by quoting into JSON: --set version='\"1.0\"'.

Dotted paths nest, so keys containing a literal dot are not addressable from
--set; use a file."
    )]
    pub set: Vec<PathLeaf<String>>,

    /// Output format; required when inputs are mixed
    #[arg(short = 'f', long, value_name = "FORMAT")]
    pub format: Option<Format>,

    /// Directory for generated Cartesian-product files
    #[arg(
        short = 'o',
        long,
        value_name = "DIR",
        long_help = "\
Directory for files generated by Cartesian-product mode. Required when a
positional `x` is present, and invalid otherwise. Existing files are never
overwritten. Output names join the selected input stems and optional --set
expression with `+`, percent-encoding unsafe bytes."
    )]
    pub output_dir: Option<PathBuf>,

    /// Error when a layer changes the type of an existing key
    #[arg(long)]
    pub strict: bool,

    /// Disable pretty-printing
    #[arg(long)]
    pub compact: bool,
}
